[versions]
project = "2.2.20-SNAPSHOT"

kotlin = "2.2.20"
dokka = "2.1.0"
buildconfig = "5.6.7"
credentials = "3.0"

ksj = "1.9.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ksj" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multi = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
credentials = { id = "nu.studer.credentials", version.ref = "credentials" }
